### ISSUE TITLE
这支持win版goldendict吗？

### ISSUE THREAD

**Issue by VimWei** [jiazhoulvke/goldendict.vim#1]
系统是win 10， Vim 8.1，
我安装了这个插件，并打开了goldendict，但在词汇上按<F12>没有响应

不知有什么需要特别配置或要求？

**Comment by jiazhoulvke** [comment]
我是在linux下使用的，没有在win10下用过，我刚看了下，貌似win版不支持命令行查词，应该是用不了的。

**Comment by VimWei** [comment]
收到，感谢神速回复！
那我只能借助AHK来查询了

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by VimWei** [comment]
虽然用AHK实现了，但总想着精简一点不必多用第三方软件，最后用如下VIMRC配置来实现，其快捷键与调用goldendict的CTRL-C-C相呼应，缺点就是浪费了Vim中重要的CTRL-C。

若能够用< leader > gd就完美了，请高手指点

```
" GoldenDict查询
nnoremap <c-c> <esc>muyiw`u
inoremap <c-c> <esc>muyiw`ua
vnoremap <c-c> ygv

```
AHK简化版（仅适用vim的normal模式）也一并附上，供参考：

```
;Vim取词
#IfWinActive ahk_class Vim   ;适应Vim编辑器
F3::
    SwitchIME(0x04090409)   ;切换输入法为英文
    SwitchIME(dwLayout){
        HKL:=DllCall("LoadKeyboardLayout", Str, dwLayout, UInt, 1)
        ControlGetFocus,ctl,A
        SendMessage,0x50,0,HKL,%ctl%,A
    }
   Send, yiw^{c 2}
Return
#IfWinExist
```
